# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub Actions Workflow with SNOW custom tasks

# on:
#   push:
#     branches: [ main ]
#    pull_request:
#      branches: [ master ]
#   push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, synchronize, reopened]

on: workflow_dispatch
#  pull_request_target:
#    types:
#      - closed

jobs:

    build:
        # Running your workflow when a pull request merges
        # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges-1
        #if: github.event.pull_request.merged == true
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Echo Build
              run: echo build

    test:
        #if: github.event.pull_request.merged == true
        name: Test
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Echo Test
              run: echo test

    integrationTest:
        #if: github.event.pull_request.merged == true
        name: Integration Tests
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Echo Integration Test
              run: echo integrationTest

    deploy:
        #if: github.event.pull_request.merged == true
        name: Deploy
        needs: integrationTest
        runs-on: ubuntu-latest
        steps:     
            - name: Echo Deploy
              run: echo deploy

    postdeploy:
        #if: github.event.pull_request.merged == true
        name: Post Deploy
        needs: deploy
        runs-on: ubuntu-latest
        steps:
            - name: Echo Post Deploy
              run: echo postdeploy
